apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ioiv1g7iv-python 
  janus-idp.io/tekton: ioiv1g7iv-python
  backstage.io/kubernetes-id: ioiv1g7iv-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ioiv1g7iv-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml