apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ioiv1g7iv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ioiv1g7iv-python 
  name: ioiv1g7iv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ioiv1g7iv-python 
